let warriors_five = {
    data(){
        return{
            five_warriors:[
                {
                    name : '关兴&张苞',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '3',
                    cost : '4',
                    img : require('../assets/warrior_cards/Screenshot_20220114_123124_com.netease.stzb.netea(1).jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '颜良&文丑',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '3',
                    cost : '4',
                    img : require('../assets/warrior_cards/Screenshot_20220125_111749_com.netease.stzb.netea.jpg') ,
                    sign : 's3',
                    getLevel : 2
                },
                {
                    name : '荀彧&荀攸',
                    star : 5,
                    camp : '魏',
                    arms : '步',
                    att : '3',
                    cost : '4',
                    img : require('../assets/warrior_cards/Screenshot_20220125_003052_com.netease.stzb.netea.jpg') ,
                    sign : 'ex',
                    getLevel : 2
                },
                {
                    name : '袁绍',
                    star : 5,
                    camp : '群',
                    arms : '弓',
                    att : '3',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_132836_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '吕布',
                    star : 5,
                    camp : '群',
                    arms : '弓',
                    att : '4',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/3CA0F0F271E962FE25A56AE277BBFD95.jpg') ,
                    sign : 's2',
                    getLevel : 1
                },
                {
                    name : '兀突骨',
                    star : 5,
                    camp : '群',
                    arms : '步',
                    att : '2',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_153916_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '华雄',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '2',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_153922_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '张辽',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '3',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154040_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '曹操',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '2',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154047_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '沙摩柯',
                    star : 5,
                    camp : '蜀',
                    arms : '弓',
                    att : '3',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154053_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '赵云',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '3',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154058_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '刘备',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '3',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154102_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '张飞',
                    star : 5,
                    camp : '蜀',
                    arms : '骑',
                    att : '2',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154106_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '吕蒙',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '4',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154110_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '大乔&小乔',
                    star : 5,
                    camp : '吴',
                    arms : '步',
                    att : '2',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154114_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '孙坚',
                    star : 5,
                    camp : '吴',
                    arms : '步',
                    att : '3',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154118_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '灵帝',
                    star : 5,
                    camp : '汉',
                    arms : '弓',
                    att : '4',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154122_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '吕布',
                    star : 5,
                    camp : '汉',
                    arms : '骑',
                    att : '3',
                    cost : '3.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154126_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '于吉',
                    star : 5,
                    camp : '群',
                    arms : '弓',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154130_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '张宝',
                    star : 5,
                    camp : '群',
                    arms : '弓',
                    att : '4',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154135_com.netease.stzb.netea.jpg') ,
                    sign : 'sp',
                    getLevel : 3
                },
                {
                    name : '陈宫',
                    star : 5,
                    camp : '群',
                    arms : '弓',
                    att : '4',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154138_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '吕姬',
                    star : 5,
                    camp : '群',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154143_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '张梁',
                    star : 5,
                    camp : '群',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154147_com.netease.stzb.netea.jpg') ,
                    sign : 'sp',
                    getLevel : 3
                },
                {
                    name : '孟获',
                    star : 5,
                    camp : '群',
                    arms : '步',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154152_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '张宁',
                    star : 5,
                    camp : '群',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154156_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '贾诩',
                    star : 5,
                    camp : '群',
                    arms : '步',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154200_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '公孙瓒',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154204_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '高顺',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154208_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '张绣',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '1',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154212_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '张郃',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154216_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '庞德',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154221_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '科比能',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154225_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '木鹿大王',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154229_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '马超',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154233_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '董卓',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '1',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154237_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '贾诩',
                    star : 5,
                    camp : '魏',
                    arms : '弓',
                    att : '4',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154241_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '乐进',
                    star : 5,
                    camp : '魏',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154244_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '曹仁',
                    star : 5,
                    camp : '魏',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154249_com.netease.stzb.netea.jpg') ,
                    sign : 'sp',
                    getLevel : 2
                },
                {
                    name : '荀攸',
                    star : 5,
                    camp : '魏',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154253_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '典韦',
                    star : 5,
                    camp : '魏',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154258_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 3
                },
                {
                    name : '郝昭',
                    star : 5,
                    camp : '魏',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154302_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '许褚',
                    star : 5,
                    camp : '魏',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154306_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '司马懿',
                    star : 5,
                    camp : '魏',
                    arms : '步',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154310_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '邓艾',
                    star : 5,
                    camp : '魏',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154314_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '曹彰',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154318_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '曹纯',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/syimg.3dmgame_edit_708848227934542.jpg') ,
                    sign : 's3',
                    getLevel : 2
                },
                {
                    name : '郭嘉',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220125_002954_com.netease.stzb.netea.jpg') ,
                    sign : 's2',
                    getLevel : 2
                },
                {
                    name : '徐晃',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154322_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '夏侯惇',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '1',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154326_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '夏侯渊',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154330_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '关羽',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '1',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154334_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '荀彧',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154338_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '夏侯霸',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154342_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '魏延',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154346_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '黄忠',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '1',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154350_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '关银屏',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154354_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '诸葛亮',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154358_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '严颜',
                    star : 5,
                    camp : '蜀',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154401_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '马岱',
                    star : 5,
                    camp : '蜀',
                    arms : '骑',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154405_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '法正',
                    star : 5,
                    camp : '蜀',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154409_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '徐庶',
                    star : 5,
                    camp : '蜀',
                    arms : '骑',
                    att : '1',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154413_com.netease.stzb.netea.jpg') ,
                    sign : 'sp',
                    getLevel : 1
                },
                {
                    name : '关羽',
                    star : 5,
                    camp : '蜀',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154417_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '庞统',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220125_111818_com.netease.stzb.netea.jpg') ,
                    sign : 's2',
                    getLevel : 2
                },
                {
                    name : '诸葛亮',
                    star : 5,
                    camp : '蜀',
                    arms : '弓',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220125_114257_com.netease.stzb.netea.jpg') ,
                    sign : 's3',
                    getLevel : 1
                },
                {
                    name : '陆逊',
                    star : 5,
                    camp : '吴',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220125_111656_com.netease.stzb.netea.jpg') ,
                    sign : 's2',
                    getLevel : 2
                },
                {
                    name : '蒋钦',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '4',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_154421_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '孙鲁班',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '4',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155006_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '张昭',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155150_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '凌统',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155155_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '诸葛恪',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155158_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '周瑜',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '4',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220125_160136_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '孙权',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '4',
                    cost : '4',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155205_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '程普',
                    star : 5,
                    camp : '吴',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155210_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '周泰',
                    star : 5,
                    camp : '吴',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155213_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '黄盖',
                    star : 5,
                    camp : '吴',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155218_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '陆抗',
                    star : 5,
                    camp : '吴',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155221_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '甘宁',
                    star : 5,
                    camp : '吴',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155225_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '孙策',
                    star : 5,
                    camp : '吴',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155228_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '刘表',
                    star : 5,
                    camp : '汉',
                    arms : '弓',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155234_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '朱儁',
                    star : 5,
                    camp : '汉',
                    arms : '弓',
                    att : '4',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155246_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '张机',
                    star : 5,
                    camp : '汉',
                    arms : '弓',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155250_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '皇甫嵩',
                    star : 5,
                    camp : '汉',
                    arms : '步',
                    att : '3',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155254_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '华佗',
                    star : 5,
                    camp : '汉',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155257_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '袁绍',
                    star : 5,
                    camp : '汉',
                    arms : '步',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155302_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '潘凤',
                    star : 5,
                    camp : '汉',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155306_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '董卓',
                    star : 5,
                    camp : '汉',
                    arms : '步',
                    att : '4',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220125_111804_com.netease.stzb.netea.jpg') ,
                    sign : 's2',
                    getLevel : 1
                },
                {
                    name : '卢植',
                    star : 5,
                    camp : '汉',
                    arms : '骑',
                    att : '1',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155309_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '李儒',
                    star : 5,
                    camp : '群',
                    arms : '弓',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155313_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '董白',
                    star : 5,
                    camp : '群',
                    arms : '弓',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155317_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '貂蝉',
                    star : 5,
                    camp : '群',
                    arms : '步',
                    att : '2',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155321_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '祝融夫人',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155325_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '张角',
                    star : 5,
                    camp : '群',
                    arms : '骑',
                    att : '2',
                    cost : '3',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155329_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '郭皇后',
                    star : 5,
                    camp : '魏',
                    arms : '弓',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155333_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '王朗',
                    star : 5,
                    camp : '魏',
                    arms : '弓',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155337_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 2
                },
                {
                    name : '张春华',
                    star : 5,
                    camp : '魏',
                    arms : '弓',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155341_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '曹丕',
                    star : 5,
                    camp : '魏',
                    arms : '弓',
                    att : '4',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155345_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '张郃',
                    star : 5,
                    camp : '魏',
                    arms : '步',
                    att : '2',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155349_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '曹植',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155354_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '张姬',
                    star : 5,
                    camp : '蜀',
                    arms : '弓',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155358_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '姜维',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '2',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155403_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '黄月英',
                    star : 5,
                    camp : '蜀',
                    arms : '步',
                    att : '2',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155406_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '马云禄',
                    star : 5,
                    camp : '蜀',
                    arms : '骑',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155410_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '小乔',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '2',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155413_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 1
                },
                {
                    name : '步皇后',
                    star : 5,
                    camp : '吴',
                    arms : '步',
                    att : '2',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/buhuanghou.jpg') ,
                    sign : 's3',
                    getLevel : 3
                },
                {
                    name : '太史慈',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '5',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155417_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '孙尚香',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '4',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155421_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '周姬',
                    star : 5,
                    camp : '吴',
                    arms : '弓',
                    att : '2',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155425_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '大乔',
                    star : 5,
                    camp : '吴',
                    arms : '步',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155429_com.netease.stzb.netea.jpg') ,
                    sign : 'xp',
                    getLevel : 1
                },
                {
                    name : '何太后',
                    star : 5,
                    camp : '汉',
                    arms : '弓',
                    att : '3',
                    cost : '2.5',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155432_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '貂蝉',
                    star : 5,
                    camp : '汉',
                    arms : '弓',
                    att : '3',
                    cost : '2',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155438_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '甄洛',
                    star : 5,
                    camp : '群',
                    arms : '弓',
                    att : '3',
                    cost : '2',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155442_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
                {
                    name : '卞夫人',
                    star : 5,
                    camp : '魏',
                    arms : '骑',
                    att : '2',
                    cost : '2',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155445_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 2
                },
                {
                    name : '蔡文姬',
                    star : 5,
                    camp : '汉',
                    arms : '骑',
                    att : '2',
                    cost : '2',
                    img : require('../assets/warrior_cards/Screenshot_20220122_155450_com.netease.stzb.netea.jpg') ,
                    sign : '',
                    getLevel : 3
                },
            ]
        }
    }
}

export default warriors_five